services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 7011:9000
      # - 7012:7000
      # - 7013:7001
    command: cross-env npm run build:server
    volumes:
      - .:/app
      - /app/node_modules
      # - ./data:/data
      # - ./admin/src:/admin/src
    env_file:
      - .env
    # labels:
    #   - "traefik.enable=true"
    #   - "traefik.http.routers.app.rule=Host(`app.localhost`)"
    #   - "traefik.http.routers.app.entrypoints=web"
    #   - "traefik.http.routers.app.service=app"
    #   - "traefik.http.services.app.loadbalancer.server.port=7000"

  # traefik:
  #   image: traefik:v2.10
  #   ports:
  #     - 8080:80
  #   volumes:
  #     - /var/run/docker.sock:/var/run/docker.sock
  #   command: --api.dashboard=true --api.insecure=true --providers.docker=true
  #   labels:
  #     - "traefik.enable=true"
  #     - "traefik.http.routers.traefik.rule=Host(`traefik.localhost`)"
  #     - "traefik.http.routers.traefik.entrypoints=web"
  #     - "traefik.http.routers.traefik.service=api@internal"