services:
  medusa:
    build: .
    ports:
      - "7011:9000"
      - "7012:7000"
      - "7013:7001"
    command: npm run dev
    volumes:
      - ./data:/data
      - ./admin/src:/admin/src
    env_file:
      - .env
